name: Automate Spond Login and Booking
on:
    schedule:
      - cron: '59 19 * * 0'
    workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run script
        env:
            MY_EMAIL: ${{ secrets.MY_EMAIL }}
            MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: python main.py