name: Automate Spond Login and Booking

on:
  schedule:
    - cron: '59 19 * * 0'  # Runs at 19:59 every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1.1
        with:
          chrome-version: 'latest'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: |
          python -m webdriver_manager.chrome
          python main.py  
