name: Automate Spond Login and Booking

on:
  schedule:
    - cron: '59 19 * * 0'  # Runs at 19:59 every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Install all necessary packages
        run: pip install selenium webdriver_manager

      - name: Run script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: python main.py