name: Automate Spond Login and Booking

on:
  schedule:
    - cron: '59 19 * * 0'  # Runs at 19:59 every Sunday
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.11 
        - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1.1
        with:
            chrome-version: 'latest' 
    
        - name: Run Selenium tests
        run: |
            python -m webdriver_manager.chrome
            python main.py 