name: Automate Spond Login and Booking

on:
  schedule:
    - cron: '59 19 * * 0'  # Runs at 19:59 every Sunday
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            MY_EMAIL: ${{ secrets.MY_EMAIL }}
            MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        steps:
            - name: Checking out repo
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12
            - name: Install dependencies
              run: | 
                python -m pip install --upgrade
                pip install -r requirements.txt
            - name: Install SeleniumBase
              run: | 
                python setup.py install
            - name: Lint with flake8
              run: | 
                pip install flake8
                flake8 . --count --show-source --statistics --exclude=temp
            - name: Install Chrome
              run: | 
                sudo apt install google-chrome-stable
            - name: Check the console scripts interface
              run: | 
                seleniumbase
                sbase
            - name: Install chrome driver
              run: | 
                seleniumbase install chromedriver
            - name: Make sure pytest is working
              run: |
                echo "def test_1(): pass" > nothing.py
                pytest nothing.py
            - name: Make sure nosetests is working
              run: |
                echo "def test_2(): pass" > nothing2.py
                nosetests nothing2.py
            - name: Run script
              run: | 
                python main.py


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checking out repo
#     uses: actions/checkout@v3

#     - name: Setting up Python
#     uses: actions/setup-python@v4
#     with:
#         python-version: '3.9'  # Ensure this matches the Python version you use locally

#     - name: Install Chrome and ChromeDriver
#     uses: browser-actions/setup-chrome@v1.1
#     with:
#         chrome-version: 'latest'  # Or specify a specific version

#     - name: Install dependencies
#     run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt  # Ensure this file lists all necessary packages

#     - name: Run script
#     env:
#         MY_EMAIL: ${{ secrets.MY_EMAIL }}
#         MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
#     run: |
#         python -m webdriver_manager.chrome
#         python main.py  # Ensure your Python script is correctly set up to use these environment variables
