name: Automate Spond Login and Booking

on:
  schedule:
    - cron: '59 19 * * 0'  # Runs at 19:59 every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installed package list
        run: apt list --installed

      - name: Install all necessary packages
        run: pip install -r requirements.txt

      - name: Run script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: python main.py

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt  

      # - name: Run script
      #   env:
      #     MY_EMAIL: ${{ secrets.MY_EMAIL }}
      #     MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
      #   run: |
      #     python -m webdriver_manager.chrome
      #     python main.py  
