name: Automate Spond Login and Booking

on:
  schedule:
    - cron: '59 19 * * 0'
  workflow_dispatch:

jobs:
  automate_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: 
            pip install -r requirements.txt
            pip install --upgrade webdriver-manager

      - name: Run script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: python main.py
