name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install -r requirements.txt

    - name: Set up Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Set up ChromeDriver
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
      with:
        version: 'latest'

    - name: Run script
      env:
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
      run: python main.py
